[MFLOG|0|2022-08-12T18:45:56.483425Z|runtime|1653f492-0a90-4675-8d4c-0004fe23b085]<flow TrainTestFlow step feature_encoding_scaling[0] (input: 1)> failed:
[MFLOG|0|2022-08-12T18:45:56.492715Z|runtime|172a4bd1-1406-4c79-9294-8aacd9f07190]    Internal error
[MFLOG|0|2022-08-12T18:45:56.493348Z|runtime|f20b39b6-47bc-4b1a-9ccc-65f31526a63d]Traceback (most recent call last):
[MFLOG|0|2022-08-12T18:45:56.493486Z|runtime|c6a3168d-0086-4dc3-ac19-d6cb05b9c11f]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/cli.py", line 1160, in main
[MFLOG|0|2022-08-12T18:45:56.493634Z|runtime|1d11f55d-2655-48c0-a74e-cd56db250dcd]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2022-08-12T18:45:56.493773Z|runtime|d7190a90-9ec7-454f-a8b0-79382fa848b9]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2022-08-12T18:45:56.493879Z|runtime|bd51869f-156a-4f67-a9fe-654c265649e0]    return self.main(args, kwargs)
[MFLOG|0|2022-08-12T18:45:56.652828Z|runtime|c81a274d-a068-47e7-861e-bb819cecd569]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2022-08-12T18:45:56.653013Z|runtime|49fad8f8-9588-409e-88d1-f4bc42f24590]    rv = self.invoke(ctx)
[MFLOG|0|2022-08-12T18:45:56.653130Z|runtime|f1193d8f-71f9-44b7-93c3-07d3064584af]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2022-08-12T18:45:56.653225Z|runtime|f114edcc-1468-405e-8774-9abb6422b79a]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2022-08-12T18:45:56.653315Z|runtime|511a03cd-e259-4035-9354-560e2fc20085]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2022-08-12T18:45:56.653404Z|runtime|01745aae-f4a1-4ae5-99f7-4feba2f80812]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2022-08-12T18:45:56.653492Z|runtime|ed0dd475-c9d1-46d4-ab0e-242716aacd39]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2022-08-12T18:45:56.653580Z|runtime|92d84940-1ec5-4229-9a87-acdf5eec3748]    return callback(args, kwargs)
[MFLOG|0|2022-08-12T18:45:56.653655Z|runtime|e183c582-f8ea-4cb1-9b09-aa44a3c69ee5]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2022-08-12T18:45:56.653733Z|runtime|b17baaf2-0936-452e-b434-600258a4ce45]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2022-08-12T18:45:56.653832Z|runtime|07c299f1-933d-4f3f-a359-2804075cb4d1]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/cli.py", line 569, in step
[MFLOG|0|2022-08-12T18:45:56.653915Z|runtime|191d8764-a6d6-40ab-9298-4dc36b92a300]    task.run_step(
[MFLOG|0|2022-08-12T18:45:56.654003Z|runtime|530b023e-4147-4a8a-b5a4-31fc516cf066]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/task.py", line 585, in run_step
[MFLOG|0|2022-08-12T18:45:56.654089Z|runtime|826123d3-ac81-4eb7-aab5-e5fef876429d]    self._exec_step_function(step_func)
[MFLOG|0|2022-08-12T18:45:56.654174Z|runtime|8f5e996d-8b2b-419b-bff0-b4e6930c4b24]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/task.py", line 59, in _exec_step_function
[MFLOG|0|2022-08-12T18:45:56.654241Z|runtime|56b55e9f-74a3-4fea-8e0d-e6054b73321c]    step_function()
[MFLOG|0|2022-08-12T18:45:56.654306Z|runtime|2532fb0e-1eca-43d6-a897-6d6a80798c24]  File "train_test_pipe.py", line 146, in feature_encoding_scaling
[MFLOG|0|2022-08-12T18:45:56.654372Z|runtime|0dcd20e3-348c-48b5-bf2f-da4293350e64]    self.features = final_features(train, new_cat, self.new_num, self.binary)  # REMOVE COLUMNS WITH UNIQUE VALUE
[MFLOG|0|2022-08-12T18:45:56.654439Z|runtime|4bd71a68-d78e-4df7-848d-fe8235c2363e]  File "/home/skyolia/anaconda3/lib/python3.8/site-packages/metaflow/flowspec.py", line 223, in __getattr__
[MFLOG|0|2022-08-12T18:45:56.654504Z|runtime|c08aabd2-5236-4d97-85e7-d59af8b8da67]    raise AttributeError("Flow %s has no attribute '%s'" % (self.name, name))
[MFLOG|0|2022-08-12T18:45:56.654569Z|runtime|e0930954-6d94-478e-a2c8-3221899b6e84]AttributeError: Flow TrainTestFlow has no attribute 'new_num'
[MFLOG|0|2022-08-12T18:45:56.654635Z|runtime|37834e80-c8a3-4d61-a02c-ca1b234b46ef]
[MFLOG|0|2022-08-12T18:45:56.654919Z|runtime|3ec71325-220c-49fb-8920-b9c5d0eee69d]Task failed.